######################################################################
##
## Filename: latchtop_latchtop_sch_tb.udo
## Created on: Mon Apr 08 19:12:18 中国标准时间 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
