######################################################################
##
## Filename: test_sel.udo
## Created on: Sun Mar 31 10:25:31 中国标准时间 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
