######################################################################
##
## Filename: test_latch.udo
## Created on: Sat Mar 30 11:10:23 中国标准时间 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
